services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/sql-scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  backend:
    image: plant-waterer/backend
    restart: always
    ports:
      - '10000:10000'
  frontend:
    image: plant-waterer/frontend
    restart: always
    ports:
      - '3000:3000'
